sources:
  - name: UploadFiles
    handler:
      graphql:
        endpoint: http://localhost:3001/graphql
  - name: ResizeImages
    handler:
      graphql:
        endpoint: http://localhost:3002/graphql

additionalTypeDefs: |
  extend type FileResult {
    thumbnailImage(width: Int, height: Int): String @resolveTo(
      requiredSelectionSet: "{ thumbnailImage }",
      sourceName: "ResizeImages",
      sourceTypeName: "Query",
      sourceFieldName: "resizeImage",
      sourceArgs: {
        image: "{root.base64}"
        width: "{args.width}"
        height: "{args.height}"
      }
    )
  }
