sources:
  - name: GraphQLAPI
    handler:
      graphql:
        endpoint: '{env.GRAPHQL_API}'
        # Use some fetch strategy
        timeout: 2000
        retry: 2

plugins:
  - rateLimit:
      config:
        - type: Query
          field: '*'
          max: 3
          ttl: 10000
          identifier: 'context.headers.host'
  - depthLimit:
      maxDepth: 5
  - responseCache:
      ttlPerCoordinate:
        - coordinate: Query.*
          ttl: 3600

cache:
  cfwKv:
    namespace: MESH
